(() => {
  'use strict';
  const core = window.CampusCore;
  const main = document.getElementById('main');
  const dialog = document.getElementById('record-dialog');
  const form = document.getElementById('record-form');
  const fields = document.getElementById('form-fields');
  const title = document.getElementById('dialog-title');
  const error = document.getElementById('form-error');
  const authGate = document.getElementById('auth-gate');
  const authForm = document.getElementById('auth-form');
  let currentUser = null;
  let registering = false;
  let state = loadState();
  let dialogContext = null;

  function loadState() {
    try {
      localStorage.removeItem('campusflow-v1');
      const stored = localStorage.getItem(core.STORAGE_KEY);
      return stored ? core.validateState(JSON.parse(stored)) : core.seed();
    } catch (e) { return core.seed(); }
  }
  function persist() { localStorage.setItem(core.STORAGE_KEY, JSON.stringify(state)); }
  function esc(value) { return String(value ?? '').replace(/[&<>"']/g, c => ({ '&':'&amp;', '<':'&lt;', '>':'&gt;', '"':'&quot;', "'":'&#39;' }[c])); }
  function money(value) { return new Intl.NumberFormat('en-IN', { style: 'currency', currency: 'INR', maximumFractionDigits: 0 }).format(value || 0); }
  function date(value) { return value ? new Intl.DateTimeFormat('en-IN', { day:'2-digit', month:'short', year:'numeric' }).format(new Date(`${value}T00:00:00`)) : '-'; }
  function relative(value) { const delta = Date.now() - new Date(value).getTime(); if (delta < 60000) return 'Just now'; if (delta < 3600000) return `${Math.floor(delta / 60000)} min ago`; return date(value.slice(0, 10)); }
  function course(id) { return state.courses.find(item => item.id === id); }
  function student(id) { return state.students.find(item => item.id === id); }
  function faculty(id) { return state.faculty.find(item => item.id === id); }
  function totalCollected() { return state.payments.reduce((sum, payment) => sum + Number(payment.amount || 0), 0); }
  function selectOptions(items, valueKey, label, selected = '') { return items.map(item => `<option value="${esc(item[valueKey])}" ${item[valueKey] === selected ? 'selected' : ''}>${esc(label(item))}</option>`).join(''); }
  function button(label, action, kind = 'primary') { return `<button class="button ${kind}" data-action="${action}">${label}</button>`; }
  function empty(message, action) { return `<div class="empty-state"><strong>${message}</strong><p>There is nothing here yet.</p>${action ? button('Add first record', action) : ''}</div>`; }
  function pageHeading(heading, description, action) { return `<div class="page-heading"><div><p class="eyebrow">CAMPUSFLOW WORKSPACE</p><h1>${heading}</h1><p>${description}</p></div><div class="heading-actions">${action || ''}</div></div>`; }
  function panel(heading, body, extra = '') { return `<section class="panel"><div class="panel-header"><div><h2>${heading}</h2></div>${extra}</div>${body}</section>`; }
  function table(headers, rows, emptyMessage = 'No records found.') { return `<div class="table-wrap"><table><thead><tr>${headers.map(h => `<th>${h}</th>`).join('')}</tr></thead><tbody>${rows || `<tr><td colspan="${headers.length}">${emptyMessage}</td></tr>`}</tbody></table></div>`; }
  function commit(next, message) { state = next; toast(message); render(); }
  function toast(message) { const node = document.getElementById('toast'); node.textContent = message; node.classList.add('show'); setTimeout(() => node.classList.remove('show'), 2600); }
  async function request(path, options = {}) { const response = await fetch(path, { credentials: 'same-origin', headers: { 'Content-Type': 'application/json', ...(options.headers || {}) }, ...options }); const data = await response.json().catch(() => ({})); if (!response.ok) throw new Error(data.error?.message || 'Request failed.'); return data; }
  function updateIdentity() { const name = currentUser?.display_name || 'Administrator'; const initials = name.split(/\s+/).map(part => part[0]).join('').slice(0, 2).toUpperCase(); document.getElementById('user-avatar').textContent = initials; document.getElementById('top-avatar').textContent = initials; document.getElementById('user-profile').innerHTML = `${esc(name)}<small id="user-role">${esc(currentUser?.role || 'owner')} · ${esc(currentUser?.organization_name || '')}</small>`; }
  function showAuth() { authGate.hidden = false; document.querySelector('.sidebar').hidden = true; document.querySelector('.app-shell').hidden = true; }
  function hideAuth() { authGate.hidden = true; document.querySelector('.sidebar').hidden = false; document.querySelector('.app-shell').hidden = false; updateIdentity(); }
  function setAuthMode(register) { registering = register; document.querySelectorAll('.auth-register-field').forEach(field => { field.hidden = !register; field.querySelector('input').required = register; }); document.getElementById('auth-title').textContent = register ? 'Create college workspace' : 'Sign in to CampusFlow'; document.getElementById('auth-copy').textContent = register ? 'Set up the first owner account for your college.' : 'Use your college account to access the workspace.'; document.getElementById('auth-submit').textContent = register ? 'Create workspace' : 'Sign in'; document.getElementById('auth-toggle').textContent = register ? 'Already have an account? Sign in' : 'Create a college workspace'; }
  async function hydrate() { const [facultyData, courseData, studentData, attendanceData, paymentData] = await Promise.all([request('/api/faculty'), request('/api/courses'), request('/api/students'), request('/api/attendance'), request('/api/payments')]); state = { version: 1, faculty: facultyData.data || [], courses: courseData.data || [], students: studentData.data || [], attendance: attendanceData.data || [], payments: (paymentData.data || []).map(payment => ({ ...payment, amount: Number(payment.amount || 0) })), activity: [] }; }
  async function initializeAuth() { try { const data = await request('/api/me'); currentUser = data.user; await hydrate(); hideAuth(); render(); } catch { showAuth(); } }
  async function renderPrincipal() {
    try {
      const data = await request('/api/staff');
      const members = Array.isArray(data.data) ? data.data : [];
      const roleCounts = members.reduce((acc, member) => {
        acc[member.role] = (acc[member.role] || 0) + 1;
        return acc;
      }, {});
      const activeStudents = state.students.filter(student => student.status === 'Active').length;
      const presentToday = state.attendance.filter(entry => entry.date === core.dateKey() && entry.status === 'Present').length;
      const collectedAmount = totalCollected();
      const totalOutstanding = state.students.reduce((sum, student) => sum + core.balance(state, student.id), 0);
      const summaryCards = [
        { label: 'Connected staff', value: members.length, detail: `${roleCounts.principal || 0} principal access` },
        { label: 'Active students', value: activeStudents, detail: `${presentToday} present today` },
        { label: 'Collections', value: money(collectedAmount), detail: `${money(totalOutstanding)} outstanding` },
        { label: 'Protected roles', value: `${(roleCounts.owner || 0) + (roleCounts.principal || 0)}`, detail: 'Owner + principal' }
      ];
      const focusPoints = [
        { label: 'Leadership coverage', value: `${members.length} people` },
        { label: 'Daily attendance', value: `${presentToday}/${Math.max(activeStudents, 1)} present` },
        { label: 'Fee health', value: totalOutstanding > 0 ? `${money(totalOutstanding)} pending` : 'All clear' },
        { label: 'Academic structure', value: `${state.courses.length} courses` }
      ];
      const rows = members.map(item => {
        const roleLabel = item.role === 'owner' ? 'Owner' : item.role === 'principal' ? 'Principal' : item.role === 'administrator' ? 'Administrator' : item.role === 'faculty' ? 'Faculty' : item.role === 'accountant' ? 'Accountant' : 'Read-only';
        const badge = item.role === 'owner' ? 'owner' : item.role === 'principal' ? 'principal' : item.role === 'administrator' ? 'admin' : item.role === 'faculty' ? 'faculty' : item.role === 'accountant' ? 'accountant' : 'viewer';
        return `<tr><td><div class="staff-person"><strong>${esc(item.displayName)}</strong><small>${esc(item.email)}</small></div></td><td><code>${esc(item.employeeId)}</code></td><td><span class="staff-role ${badge}">${esc(roleLabel)}</span></td><td>${item.role === 'owner' ? '<span class="staff-protected">Protected</span>' : `<button class="table-action danger" data-action="remove-staff" data-id="${item.id}">Remove</button>`}</td></tr>`;
      }).join('');
      main.innerHTML = pageHeading('Principal office', 'Track access, leadership coverage and connected staff in one clear workspace.', button('Add staff', 'add-staff')) +
        `<div class="principal-shift"><section class="principal-panel principal-hero"><div class="principal-hero-copy"><p class="eyebrow">LEADERSHIP OVERVIEW</p><h2>Campus decisions need a clear line of control.</h2><p>Review staffing, daily attendance and financial signals from a single desk.</p></div><div class="principal-hero-actions"><button class="button primary" data-action="add-staff">Add staff</button><button class="button secondary" data-action="add-student">Add student</button></div></section><aside class="principal-panel principal-actions"><h3>Quick actions</h3><button class="action-link" data-action="add-student">New student</button><button class="action-link" data-action="add-course">New course</button><button class="action-link" data-action="add-faculty">New faculty</button><button class="action-link" data-action="save-attendance">Save attendance</button></aside></div>` +
        `<div class="principal-stats">${summaryCards.map(card => `<article class="principal-stat"><span class="principal-stat-label">${esc(card.label)}</span><strong class="principal-stat-value">${esc(card.value)}</strong><small>${esc(card.detail)}</small></article>`).join('')}</div>` +
        `<div class="principal-summary-grid">${focusPoints.map(point => `<article class="principal-focus"><span>${esc(point.label)}</span><strong>${esc(point.value)}</strong></article>`).join('')}</div>` +
        panel('Leadership access overview', table(['Name', 'Employee ID', 'Role', 'Action'], rows), `<span class="panel-count">${members.length} connected</span>`);
    } catch {
      main.innerHTML = pageHeading('Principal office', 'Staff access is restricted to principal and owner accounts for secure leadership management.', '');
    }
  }
  function setActive(route) { document.querySelectorAll('[data-nav]').forEach(link => link.classList.toggle('active', link.dataset.nav === route)); document.getElementById('breadcrumb').textContent = route === 'dashboard' ? 'Overview' : route === 'settings' ? 'Settings & backups' : route === 'principal' ? 'Principal office' : route[0].toUpperCase() + route.slice(1); }
  function render() { const route = location.hash.slice(1).split('?')[0] || 'dashboard'; if (dialog.open) dialog.close(); setActive(route); document.getElementById('student-count').textContent = state.students.length; document.getElementById('today-label').textContent = new Intl.DateTimeFormat('en-IN', { weekday:'short', day:'numeric', month:'short' }).format(new Date()); const views = { dashboard: renderDashboard, students: renderStudents, faculty: renderFaculty, courses: renderCourses, attendance: renderAttendance, fees: renderFees, settings: renderSettings }; if (route === 'principal') renderPrincipal(); else (views[route] || renderDashboard)(); }

  function renderDashboard() {
    const active = state.students.filter(s => s.status === 'Active').length;
    const present = state.attendance.filter(a => a.date === core.dateKey() && a.status === 'Present').length;
    const collected = totalCollected();
    const due = state.students.reduce((sum, s) => sum + core.balance(state, s.id), 0);
    const recent = state.activity.slice(0, 6).map(item => `<li><span class="activity-dot"></span><div>${esc(item.message)}<small>${relative(item.at)}</small></div></li>`).join('');
    const courseRows = state.courses.map(c => { const count = state.students.filter(s => s.courseId === c.id).length; return `<div class="course-row"><span class="course-mark">${esc(c.code.slice(0, 2))}</span><div><strong>${esc(c.name)}</strong><small>${count} students · ${c.credits} credits</small></div><b>${money(c.fee)} / ${esc((c.feeCycle || 'Yearly').toLowerCase())}</b></div>`; }).join('');
    main.innerHTML = pageHeading('Good morning, Administrator', 'Here is what is happening across Greenfield College today.', button('Add student', 'add-student')) + `<section class="welcome-banner"><div><p class="eyebrow">YOUR COLLEGE AT A GLANCE</p><h2>Everything in one calm view.</h2><p>Track students, teaching, attendance and payments from your local workspace.</p></div><div class="banner-art" aria-hidden="true">✦</div></section><div class="metrics"><div class="metric"><span class="metric-icon">♙</span><span class="metric-label">Total students</span><strong class="metric-value">${state.students.length}</strong><small class="metric-detail">${active} active learners</small></div><div class="metric"><span class="metric-icon green">◷</span><span class="metric-label">Today's attendance</span><strong class="metric-value">${present}<small>/${active}</small></strong><small class="metric-detail">${active ? Math.round(present / active * 100) : 0}% present</small></div><div class="metric"><span class="metric-icon orange">▣</span><span class="metric-label">Fees collected</span><strong class="metric-value">${money(collected)}</strong><small class="metric-detail">${money(due)} outstanding</small></div><div class="metric"><span class="metric-icon blue">▤</span><span class="metric-label">Active courses</span><strong class="metric-value">${state.courses.length}</strong><small class="metric-detail">Across ${new Set(state.courses.map(c => c.department)).size} departments</small></div></div><div class="dashboard-grid">${panel('Recent activity', `<ul class="activity-list">${recent || '<li>No activity yet.</li>'}</ul>`, '<a class="text-link" href="#settings">View settings</a>')}${panel('Course snapshot', `<div class="course-list">${courseRows}</div>`, '<a class="text-link" href="#courses">View all courses</a>')}</div>`;
  }
  function toolbar(placeholder, filter = '') { return `<div class="toolbar"><label class="search-wrap"><span>⌕</span><input data-filter="table" value="${esc(filter)}" placeholder="${placeholder}" aria-label="Search"></label><span class="result-count"></span></div>`; }
  function renderStudents() {
    main.innerHTML = pageHeading('Students', 'Manage enrollment, academic details and student status.', button('Add student', 'add-student')) + panel('Student directory', toolbar('Search by name, roll number or email'), '<span class="panel-count">' + state.students.length + ' records</span>') ;
    const panelNode = main.querySelector('.panel'); panelNode.insertAdjacentHTML('beforeend', '<div id="table-output"></div>'); drawStudents('');
  }
  function drawStudents(filter) { const rows = state.students.filter(s => `${s.name} ${s.roll} ${s.email}`.toLowerCase().includes(filter.toLowerCase())).map(s => `<tr><td><strong>${esc(s.name)}</strong><small>${esc(s.email)}</small></td><td>${esc(s.roll)}</td><td>${esc(course(s.courseId)?.code || '-')}</td><td>Year ${s.year}</td><td><span class="status ${s.status.toLowerCase().replace(' ', '-')}">${esc(s.status)}</span></td><td><button class="table-action" data-action="edit-student" data-id="${s.id}">Edit</button><button class="table-action danger" data-action="delete-student" data-id="${s.id}">Delete</button></td></tr>`).join(''); document.getElementById('table-output').innerHTML = table(['Student','Roll number','Course','Year','Status','Actions'], rows); document.querySelector('.result-count').textContent = `${state.students.filter(s => `${s.name} ${s.roll} ${s.email}`.toLowerCase().includes(filter.toLowerCase())).length} results`; }
  function renderFaculty() { const rows = state.faculty.map(f => `<tr><td><strong>${esc(f.name)}</strong><small>${esc(f.email)}</small></td><td>${esc(f.department)}</td><td>${esc(f.designation)}</td><td>${state.courses.filter(c => c.facultyId === f.id).length}</td><td><button class="table-action" data-action="edit-faculty" data-id="${f.id}">Edit</button><button class="table-action danger" data-action="delete-faculty" data-id="${f.id}">Delete</button></td></tr>`).join(''); main.innerHTML = pageHeading('Faculty', 'Keep teaching teams and course ownership up to date.', button('Add faculty', 'add-faculty')) + panel('Faculty directory', table(['Faculty member','Department','Designation','Courses','Actions'], rows), '<span class="panel-count">' + state.faculty.length + ' members</span>'); }
  function renderCourses() { const cards = state.courses.map(c => `<article class="course-card"><div class="course-card-top"><span class="course-mark">${esc(c.code.slice(0, 2))}</span><button class="more-action" data-action="edit-course" data-id="${c.id}">Edit</button></div><h2>${esc(c.name)}</h2><p>${esc(c.code)} · ${esc(c.department)}</p><div class="course-card-meta"><span>${state.students.filter(s => s.courseId === c.id).length} students</span><strong>${money(c.fee)} / ${esc((c.feeCycle || 'Yearly').toLowerCase())}</strong></div></article>`).join(''); main.innerHTML = pageHeading('Courses', 'Organize academic programs, fees and faculty assignments.', button('Add course', 'add-course')) + `<div class="course-grid">${cards || empty('No courses yet.', 'add-course')}</div>`; }
  function renderAttendance() { const today = core.dateKey(); const active = state.students.filter(s => s.status === 'Active'); const entries = active.map(s => { const record = state.attendance.find(a => a.studentId === s.id && a.date === today); return `<tr><td><strong>${esc(s.name)}</strong><small>${esc(s.roll)}</small></td><td>${esc(course(s.courseId)?.code || '-')}</td><td><select data-attendance="${s.id}">${['Unmarked','Present','Absent','Late'].map(status => `<option ${(!record && status === 'Unmarked') || record?.status === status ? 'selected' : ''}>${status}</option>`).join('')}</select></td></tr>`; }).join(''); main.innerHTML = pageHeading('Attendance', 'Mark today’s attendance for active students.', `<span class="attendance-summary">${state.attendance.filter(a => a.date === today && a.status === 'Present').length} present today</span>`) + panel(`Attendance for ${date(today)}`, `<div class="attendance-toolbar"><label>Date <input id="attendance-date" type="date" value="${today}" max="${today}"></label><button class="button primary" data-action="save-attendance">Save attendance</button><button class="button secondary" data-action="export-attendance">Export Excel</button><label class="button secondary" for="attendance-import">Import Excel</label><input id="attendance-import" type="file" accept=".csv,text/csv" hidden></div>${table(['Student','Course','Status'], entries, 'No active students to mark.')}`); }
  function renderFees() { const rows = state.students.map(s => `<tr><td><strong>${esc(s.name)}</strong><small>${esc(s.roll)}</small></td><td>${esc(course(s.courseId)?.code || '-')}</td><td>${money(course(s.courseId)?.fee)} / ${esc((course(s.courseId)?.feeCycle || 'Yearly').toLowerCase())}</td><td>${money(core.totalPaid(state, s.id))}</td><td><strong class="${core.balance(state, s.id) ? 'due' : 'paid'}">${money(core.balance(state, s.id))}</strong></td><td><button class="table-action" data-action="add-payment" data-id="${s.id}" ${core.balance(state, s.id) <= 0 ? 'disabled' : ''}>Record payment</button></td></tr>`).join(''); main.innerHTML = pageHeading('Fees & payments', 'Track semester or yearly charges and student collections.', '') + panel('Payment ledger', table(['Student','Course','Charge','Paid','Balance','Actions'], rows), '<span class="panel-count">' + money(totalCollected()) + ' collected</span>'); }
  function renderSettings() { main.innerHTML = pageHeading('Settings & backups', 'Keep this local workspace portable and easy to reset.', '') + `<div class="settings-grid"><section class="settings-card"><span class="settings-icon">⇩</span><h2>Export workspace</h2><p>Download a JSON backup of your students, courses, payments and attendance.</p>${button('Download backup', 'export-backup')}</section><section class="settings-card"><span class="settings-icon">⇧</span><h2>Restore workspace</h2><p>Load a previously exported CampusFlow backup into this browser.</p><input id="import-file" type="file" accept="application/json"><label class="button secondary" for="import-file">Choose backup</label></section><section class="settings-card"><span class="settings-icon">↻</span><h2>Clear workspace</h2><p>Remove all locally stored records and start with an empty workspace.</p>${button('Clear all records', 'reset-demo', 'secondary')}</section></div>`; }

  const definitions = {
    student: { title: 'student', type: 'students', inputs: (r = {}) => [['name','Student name','text',r.name],['roll','Roll number','text',r.roll],['email','Email address','email',r.email],['courseId','Course','select',r.courseId, selectOptions(state.courses,'id',c => `${c.code} - ${c.name}`,r.courseId)],['year','Study year','number',r.year || 1],['status','Status','select',r.status || 'Active', ['Active','Graduated','On leave'].map(v => `<option ${v === (r.status || 'Active') ? 'selected' : ''}>${v}</option>`).join('')],['joined','Enrollment date','date',r.joined || core.dateKey()]] },
    faculty: { title: 'faculty member', type: 'faculty', inputs: (r = {}) => [['name','Full name','text',r.name],['email','Email address','email',r.email],['department','Department','select',r.department, core.departments.map(v => `<option ${v === r.department ? 'selected' : ''}>${v}</option>`).join('')],['designation','Designation','text',r.designation]] },
    course: { title: 'course', type: 'courses', inputs: (r = {}) => [['name','Course name','text',r.name],['code','Course code','text',r.code],['department','Department','select',r.department, core.departments.map(v => `<option ${v === r.department ? 'selected' : ''}>${v}</option>`).join('')],['credits','Credits','number',r.credits || 1],['facultyId','Faculty lead','select',r.facultyId || '', '<option value="">Unassigned</option>' + selectOptions(state.faculty,'id',f => f.name,r.facultyId)],['fee','Fee amount (INR)','number',r.fee || 0],['feeCycle','Fee cycle','select',r.feeCycle || 'Yearly',['Semester','Yearly'].map(v => `<option ${v === (r.feeCycle || 'Yearly') ? 'selected' : ''}>${v}</option>`).join('')]] }
  };
  function openRecord(kind, record) { const definition = definitions[kind]; dialogContext = { kind, id: record?.id }; title.textContent = `${record ? 'Edit' : 'Add'} ${definition.title}`; fields.innerHTML = definition.inputs(record).map(([name, label, type, value, options]) => `<label class="field ${name === 'courseId' || name === 'department' ? 'wide' : ''}"><span>${label}</span>${type === 'select' ? `<select name="${name}">${options}</select>` : `<input name="${name}" type="${type}" value="${esc(value)}" ${name === 'credits' || name === 'year' ? 'min="1"' : ''} required>`}</label>`).join(''); error.textContent = ''; dialog.showModal(); }
  async function submitRecord(event) { event.preventDefault(); try { const input = Object.fromEntries(new FormData(form).entries()); const d = definitions[dialogContext.kind]; await request(`/api/${d.type}${dialogContext.id ? `/${dialogContext.id}` : ''}`, { method: dialogContext.id ? 'PATCH' : 'POST', body: JSON.stringify(input) }); await hydrate(); toast('Record saved'); dialog.close(); render(); } catch (e) { error.textContent = e.message; } }
  async function remove(kind, id) { const d = definitions[kind]; if (confirm(`Delete this ${d.title}?`)) { try { await request(`/api/${d.type}/${id}`, { method: 'DELETE' }); await hydrate(); toast('Record deleted'); render(); } catch (e) { toast(e.message); } } }
  async function removeStaff(id) { if (!confirm('Remove this staff member from the workspace?')) return; try { await request(`/api/staff/${id}`, { method: 'DELETE' }); await renderPrincipal(); toast('Staff member removed'); } catch (e) { toast(e.message); } }
  function openStaff() { dialogContext = { kind: 'staff' }; title.textContent = 'Add staff member'; fields.innerHTML = '<label class="field wide"><span>Registered email</span><input name="email" type="email" required></label><label class="field wide"><span>Role</span><select name="role"><option value="principal">Principal</option><option value="administrator">Administrator</option><option value="faculty">Faculty</option><option value="accountant">Accountant</option><option value="read_only">Read-only</option></select></label>'; error.textContent = ''; dialog.showModal(); }
  function download(name, content, type) { const link = document.createElement('a'); link.href = URL.createObjectURL(new Blob([content], { type })); link.download = name; link.click(); URL.revokeObjectURL(link.href); }
  function handleAction(action, id) { if (action === 'add-student') return openRecord('student'); if (action === 'add-faculty') return openRecord('faculty'); if (action === 'add-course') return openRecord('course'); if (action === 'edit-student') return openRecord('student', student(id)); if (action === 'edit-faculty') return openRecord('faculty', faculty(id)); if (action === 'edit-course') return openRecord('course', course(id)); if (action === 'delete-student') return remove('student', id); if (action === 'delete-faculty') return remove('faculty', id); if (action === 'add-payment') return openPayment(id); if (action === 'save-attendance') return saveAttendance(); if (action === 'export-attendance') return exportAttendance(); if (action === 'export-backup') return download('campusflow-backup.json', JSON.stringify(state, null, 2), 'application/json'); if (action === 'reset-demo' && confirm('Clear all locally stored records?')) { state = core.seed(); persist(); toast('Workspace cleared'); render(); } }
  function openPayment(id) { dialogContext = { kind: 'payment' }; title.textContent = 'Record payment'; fields.innerHTML = `<label class="field wide"><span>Student</span><select name="studentId">${selectOptions(state.students.filter(s => core.balance(state, s.id) > 0),'id',s => `${s.name} (${money(core.balance(state, s.id))} due)`,id)}</select></label><label class="field"><span>Amount (INR)</span><input name="amount" type="number" min="0.01" step="0.01" required></label><label class="field"><span>Payment date</span><input name="date" type="date" max="${core.dateKey()}" value="${core.dateKey()}" required></label><label class="field"><span>Method</span><select name="method">${['Bank transfer','Cash','Card','UPI'].map(v => `<option>${v}</option>`).join('')}</select></label>`; error.textContent = ''; dialog.showModal(); }
  function parseCsv(text) { const rows = []; let row = [], value = '', quoted = false; for (let index = 0; index < text.length; index += 1) { const char = text[index]; const next = text[index + 1]; if (char === '"' && quoted && next === '"') { value += '"'; index += 1; } else if (char === '"') quoted = !quoted; else if (char === ',' && !quoted) { row.push(value); value = ''; } else if ((char === '\n' || char === '\r') && !quoted) { if (char === '\r' && next === '\n') index += 1; row.push(value); if (row.some(cell => cell !== '')) rows.push(row); row = []; value = ''; } else value += char; } if (value || row.length) { row.push(value); rows.push(row); } return rows; }
  function exportAttendance() { const rows = [['Date', 'Student ID', 'Roll Number', 'Student Name', 'Course', 'Status']]; state.attendance.forEach(entry => { const record = student(entry.studentId); rows.push([entry.date, entry.studentId, record?.roll || '', record?.name || '', course(record?.courseId)?.code || '', entry.status]); }); download('attendance-sheet.csv', '\ufeff' + core.csv(rows), 'text/csv;charset=utf-8'); }
  async function importAttendance(file) { const rows = parseCsv(await file.text()); if (rows.length < 2) throw new Error('Attendance CSV is empty.'); const header = rows[0].map(value => value.trim().toLowerCase()); const dateIndex = header.indexOf('date'); const studentIdIndex = header.indexOf('student id'); const rollIndex = header.indexOf('roll number'); const statusIndex = header.indexOf('status'); if (dateIndex < 0 || statusIndex < 0 || (studentIdIndex < 0 && rollIndex < 0)) throw new Error('CSV must contain Date, Student ID or Roll Number, and Status columns.'); const grouped = new Map(); rows.slice(1).forEach(row => { const dateValue = row[dateIndex]?.trim(); const status = row[statusIndex]?.trim(); const record = student(studentIdIndex >= 0 ? row[studentIdIndex]?.trim() : ''); const matched = record || state.students.find(item => item.roll === row[rollIndex]?.trim().toUpperCase()); if (!matched || !core.validDate(dateValue) || dateValue > core.dateKey() || !['Present', 'Absent', 'Late', 'Unmarked'].includes(status)) throw new Error('CSV contains an invalid student, date, or status.'); if (!grouped.has(dateValue)) grouped.set(dateValue, []); grouped.get(dateValue).push({ studentId: matched.id, status }); }); for (const [dateValue, entries] of grouped) await request(`/api/attendance/${dateValue}`, { method: 'PUT', body: JSON.stringify(entries) }); await hydrate(); toast('Attendance imported'); render(); }
  async function saveAttendance() { try { const dateValue = document.getElementById('attendance-date').value; const entries = [...document.querySelectorAll('[data-attendance]')].map(select => ({ studentId: select.dataset.attendance, status: select.value })); await request(`/api/attendance/${dateValue}`, { method: 'PUT', body: JSON.stringify(entries) }); await hydrate(); toast('Attendance saved'); render(); } catch (e) { toast(e.message); } }
  form.addEventListener('submit', async event => { if (dialogContext?.kind === 'staff') { event.preventDefault(); try { await request('/api/staff', { method: 'POST', body: JSON.stringify(Object.fromEntries(new FormData(form).entries())) }); dialog.close(); await renderPrincipal(); toast('Staff member connected'); } catch (e) { error.textContent = e.message; } } else if (dialogContext?.kind === 'payment') { event.preventDefault(); try { const input = Object.fromEntries(new FormData(form).entries()); await request('/api/payments', { method: 'POST', headers: { 'Idempotency-Key': crypto.randomUUID() }, body: JSON.stringify(input) }); await hydrate(); toast('Payment recorded'); dialog.close(); render(); } catch (e) { error.textContent = e.message; } } else await submitRecord(event); });
  authForm.addEventListener('submit', async event => { event.preventDefault(); const authError = document.getElementById('auth-error'); authError.textContent = ''; try { const result = await request(registering ? '/api/auth/register' : '/api/auth/login', { method: 'POST', body: JSON.stringify(Object.fromEntries(new FormData(authForm).entries())) }); currentUser = result.user; hideAuth(); render(); } catch (e) { authError.textContent = e.message; } });
  document.getElementById('auth-toggle').addEventListener('click', () => setAuthMode(!registering));
  const sidebar = document.querySelector('.sidebar');
  const sidebarScrim = document.getElementById('sidebar-scrim');
  const mobileMenuButton = document.getElementById('mobile-menu-button');
  function closeMobileMenu() { sidebar.classList.remove('open'); sidebarScrim.hidden = true; mobileMenuButton?.setAttribute('aria-expanded', 'false'); }
  mobileMenuButton?.addEventListener('click', () => { const open = sidebar.classList.toggle('open'); sidebarScrim.hidden = !open; mobileMenuButton.setAttribute('aria-expanded', String(open)); });
  sidebarScrim?.addEventListener('click', closeMobileMenu);
  document.querySelectorAll('.sidebar a').forEach(link => link.addEventListener('click', closeMobileMenu));
  document.getElementById('logout-button').addEventListener('click', async () => { await request('/api/auth/logout', { method: 'POST' }).catch(() => {}); currentUser = null; setAuthMode(false); showAuth(); });
  document.getElementById('close-dialog').addEventListener('click', () => dialog.close()); document.getElementById('cancel-dialog').addEventListener('click', () => dialog.close());
  document.addEventListener('click', event => { const target = event.target.closest('[data-action]'); if (target?.dataset.action === 'add-staff') openStaff(); if (target?.dataset.action === 'remove-staff') removeStaff(target.dataset.id); if (target) handleAction(target.dataset.action, target.dataset.id); });
  document.addEventListener('input', event => { if (event.target.dataset.filter === 'table' && location.hash === '#students') drawStudents(event.target.value); });
  document.addEventListener('change', event => { if (event.target.id === 'import-file' && event.target.files[0]) { const reader = new FileReader(); reader.onload = () => { try { state = core.validateState(JSON.parse(reader.result)); persist(); toast('Backup restored'); render(); } catch (e) { toast(e.message); } }; reader.readAsText(event.target.files[0]); } if (event.target.id === 'attendance-import' && event.target.files[0]) importAttendance(event.target.files[0]).catch(e => toast(e.message)); });
  window.addEventListener('hashchange', render); setAuthMode(false); initializeAuth();
})();
